src/components/ResultsView.tsx
@dvargas92495 
https://user-images.githubusercontent.com/3792666/207988330-9efac80b-641d-4d27-b5da-8f151c084122.mp4
=> add query used to when no results found

src/utils/registerDiscourseDatalogTranslators.ts
https://user-images.githubusercontent.com/3792666/207984327-2a0d51a0-80a4-48a7-9de5-ab9a2bf7db34.mp4
=> add DG node as target when DG relation selected

src/components/ResultsView.tsx
=> pctbznlmp copy query block

src/utils/fireQuery.ts
=> alias_test, change defaultSelection label if exist

package-lock.json, package.json, src/components/ResultsView.tsx, src/index.ts
=> add page embed check and css fix

README.md, package-lock.json, package.json
=> readme update - add regex selection and edit first column header

package-lock.json, package.json, src/utils/fireQuery.ts
add case for singular `not` **node** selection
@dvargas92495
=> add case for singular not node selection

README.md, package-lock.json, package.json
@dvargas92495
Add ToC, update images, text, new demo video, add grain demo video, change some language, move some stuff, all around 🎉
=> Update qb docs 23 01

package-lock.json, package.json, src/components/ResultsView.tsx
=> Query Drawer - maximize button, quick fix (closes #39)

README.md
- added docs for #44 
- added some of the formatting from #28 while we wait on `<details>`
=> Update Docs: Smartblocks Integration + formatting

package-lock.json, package.json, src/utils/conditionToDatalog.ts
=> References title bug

src/components/QueryEditor.tsx, src/components/QueryPage.tsx, src/utils/fireQuery.ts
`true` for `Query Blocks` and `Query Pages`
=> add showAlias props closes #47

package-lock.json, package.json, src/components/QueryEditor.tsx, src/components/ResultsView.tsx, src/utils/fireQuery.ts
https://user-images.githubusercontent.com/3792666/222017936-d0d79e05-adcb-4952-81e7-db8bc41a929c.mp4
=> add copy button, fix indenting and change format on used query (Closes #42)

.github/workflows/main.yaml, package-lock.json, package.json, src/components/TldrawCanvas.tsx
https://www.loom.com/share/b249d2d7a89e4d09bce9c349694ed0b1
=> Creating and removing discourse nodes to/from canvas

src/components/TldrawCanvas.tsx, src/utils/getDiscourseRelations.ts
https://www.loom.com/share/a88cbb123df14c81a98a8d298194f682
=> Aligning discourse nodes with colors

package-lock.json, package.json, patches/@tldraw+tldraw++@tldraw+editor+2.0.0-canary.ffda4cfb.patch, patches/@tldraw+tldraw++@tldraw+ui+2.0.0-canary.ffda4cfb.patch, src/components/DiscourseNodeCanvasSettings.tsx, src/components/TldrawCanvas.tsx, src/discourseGraphsMode.ts, src/utils/getDiscourseNodes.ts
Going to be merging this later tn, since Matt is looking to test the changes locally
=> Configurable Colors and drawing edges

package-lock.json, package.json, src/components/QueryEditor.tsx, src/components/ResultsView.tsx, src/index.ts, src/utils/compileDatalog.ts, src/utils/conditionToDatalog.ts, src/utils/fireQuery.ts, src/utils/gatherDatalogVariablesFromClause.ts
https://www.loom.com/share/7ae0c6fe012547ce89bff0213ef16d83
=> Or branches

.github/workflows/main.yaml, .github/workflows/pr.yaml, package-lock.json, package.json, src/components/DiscourseNodeConfigPanel.tsx, src/components/DiscourseNodeMenu.tsx, src/components/DiscourseNodeSpecification.tsx, src/components/QueryEditor.tsx, src/components/TldrawCanvas.tsx, src/discourseGraphsMode.ts
This PR is getting rather large, so going to request review now.
The goal of this line of work is to start aligning the Canvas to be an actual representation of what's in Roam. The first step along that vein is to allow the creation of nodes in the canvas to result in new nodes in Roam
=> Start a tight coupling between canvas & graph

patches/@tldraw+primitives+2.0.0-canary.ffda4cfb.patch, patches/@tldraw+tldraw++@tldraw+editor+2.0.0-canary.ffda4cfb.patch, src/components/TldrawCanvas.tsx
https://www.loom.com/share/6cb9e231d66c4c48a702fc11ba68e1ab
=> Restricting Discourse Relations to binding to valid nodes

package-lock.json, package.json, src/components/QueryDrawer.tsx, src/components/ResultsTable.tsx, src/components/ResultsView.tsx, src/index.ts, src/utils/compileDatalog.ts, src/utils/parseResultSettings.ts
=> Migrating Results Table into its own file

package-lock.json, package.json, src/components/TldrawCanvas.tsx, src/utils/getBlockProps.ts
https://www.loom.com/share/09de0f47b802405fbd6f84992af7d60d
=> Automatically draw existing edges

package-lock.json, package.json, src/components/Charts.tsx, src/components/DiscourseContext.tsx, src/components/QueryDrawer.tsx, src/components/QueryPage.tsx, src/components/ResultsTable.tsx, src/components/ResultsView.tsx, src/utils/parseQuery.ts, src/utils/parseResultSettings.ts, src/utils/postProcessResults.ts, src/utils/types.ts
=> Supporting Adjustable widths in Result Table

package-lock.json, package.json, src/components/ResultsTable.tsx, src/index.ts
=> Page embed fix

package-lock.json, package.json, src/utils/fireQuery.ts
This PR is dependent on https://github.com/samepage-network/roam-samepage/pull/17
=> Start to stabilize cross app querying

docs/examples.md, docs/query-builder.md, package-lock.json, package.json, src/components/ResultsView.tsx
https://github.com/dvargas92495/roamjs-query-builder/blob/docs-add-examples/docs/examples.md
or a screenshot: https://github.com/dvargas92495/roamjs-query-builder/assets/3792666/4587deba-2d7c-459d-8c82-d6aed330799c
=> Add condition examples

README.md, docs/examples.md, docs/query-builder.md, package-lock.json, package.json
https://github.com/dvargas92495/roamjs-query-builder/blob/docs-add--selection-examples/docs/examples.md
=> Docs - add selection examples

package-lock.json, package.json, src/utils/predefinedSelections.ts
Took over 10 min to run on one client's graph, causing it to hang.
Going to merge right away to fix the hang
=> ATTR_SUGGESTIONS hangs graph fix

package-lock.json, package.json, src/components/DiscourseContext.tsx, src/components/ResultsTable.tsx, src/index.ts, src/utils/parseQuery.ts, src/utils/predefinedSelections.ts
[Loom](https://www.loom.com/share/cdb2c7e593f24eec8dac48fb5927adf8)
=> Nested Row Actions

package-lock.json, package.json, src/utils/predefinedSelections.ts
=> Limit action selections

package-lock.json, package.json, src/utils/runQueryTools.ts
=> TextContent error

src/components/Kanban.tsx
https://www.loom.com/share/6c89b9631f82482bad6922e1e74f201e
also fixed the spacing when adding a card from the video:
fixed:
=> kanban cards full width, minimal add button

package-lock.json, package.json, src/components/Kanban.tsx, src/components/ResultsView.tsx, src/utils/predefinedSelections.ts
https://www.loom.com/share/cc48bec4e512487ea040186ef99cbc62
- Initial Column Settings
- Display tasks if "No {columnKey}"
- Being able to select "text" (first column) as Group By or Display
=> Multiple Kanban fixes

src/components/QueryEditor.tsx, src/index.ts
https://github.com/RoamJS/query-builder/assets/3792666/9e1480a9-9ade-4a21-b996-55cfc4d971e7
=> better keyboard UX for Query Editor

package-lock.json, package.json, src/components/TldrawCanvas.tsx
=> extract menu additions to functions, remove ifs

package-lock.json, package.json, src/components/Export.tsx
Send results of query to the new Graph Overview
https://github.com/RoamJS/query-builder/assets/3792666/40c5a898-03a0-4e2e-ac7d-21ba5f373490
=> Export: Send to graph overview

package-lock.json, package.json, src/components/TldrawCanvas.tsx
move query into `<LabelDialogAutocomplete>` so that the query only fires when dialog is open
=> Refactor LabelDialog in TldrawCanvas

package-lock.json, package.json, src/components/TldrawCanvas.tsx, src/components/TldrawCanvasLabelDialog.tsx
requires https://github.com/RoamJS/roamjs-components/pull/18
Improved UX / perf for `page`, `block`, and discourse nodes with large results
=> add disabled/maxItems to canvas labelDialog

package-lock.json, package.json, src/utils/getExportTypes.ts
=> Fix export dialog null

src/utils/toCellValue.ts
https://www.loom.com/share/1450856606614a2dbedd40bd29e1b075
=> add blockUid to refs in resolveRefs

src/components/Export.tsx, src/components/TldrawCanvas.tsx, src/utils/measureCanvasNodeText.ts
https://www.loom.com/share/3a24e807cf0c494d91b910e7c1f22938
=> Consolidate measure text and svg

src/utils/conditionToDatalog.ts
Requested by Ekuboh in [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1700033855016789?thread_ts=1699538480.323519&cid=C016N2B66JU)
=> add {current} support for "with text in title"

package-lock.json, package.json, src/components/DiscourseNodeCanvasSettings.tsx, src/components/TldrawCanvas.tsx, src/components/TldrawCanvasLabelDialog.tsx, src/discourseGraphsMode.ts, src/utils/getDiscourseNodes.ts
https://www.loom.com/share/6c14c60fd1f6462ca71fd117f04734d0
=> Style dgraph nodes in Graph Overview

src/components/TldrawCanvas.tsx
=> support opening canvas node in main window

package-lock.json, package.json, src/components/DiscourseContext.tsx, src/components/DiscourseNodeCanvasSettings.tsx, src/components/TldrawCanvas.tsx, src/components/TldrawCanvasLabelDialog.tsx, src/discourseGraphsMode.ts
This PR lets the user "link" a referenced to canvas node via
- dialog create
- dialog edit
- dragging an arrow from source to target
https://www.loom.com/share/9034601384d349a4a73e0e83964d5a26
=> Ability to add source to canvas node

docs/query-builder.md, package-lock.json, package.json, src/components/DiscourseNodeCanvasSettings.tsx, src/components/ResultsTable.tsx, src/components/ResultsView.tsx, src/components/TldrawCanvas.tsx, src/components/TldrawCanvasLabelDialog.tsx, src/discourseGraphsMode.ts
https://www.loom.com/share/2fa5466894ae420abc4e348f4a51ae77
=> Add Sort to QB Menu

package-lock.json, package.json, src/components/ResultsView.tsx
https://www.loom.com/share/813dbd6bd90c45ae8539c352b499c2d4
Also - menu stays open after selecting a layout (so user can select options for the layout)
=> menu refactor / misc updates

src/components/Kanban.tsx, src/components/ResultsTable.tsx, src/components/ResultsView.tsx, src/index.ts
Just for selected `display`, not the selections yet
=> Support embed for Kanban display

src/components/Kanban.tsx, src/index.ts
and move add column button to bottom right
https://www.loom.com/share/db3106ef01db429db5d4ac77d7eb2c10
=> Kanban min column width, horizontal scroll

src/components/Kanban.tsx, src/index.ts
https://www.loom.com/share/3aac6db3b3f747f59f969e036076f3dc
`Block with uid "" could not be found.` is kind of annyoying
=> support embed for kanban selections

package-lock.json, package.json, src/components/DiscourseNodeMenu.tsx, src/components/Kanban.tsx, src/components/TldrawCanvas.tsx, src/index.ts, src/utils/formatUtils.ts
https://www.loom.com/share/74b9c222a97d4ef198ae4fd7c6c66ac5
=> Convert a canvas text node to any dgraph node

src/components/TldrawCanvas.tsx
bug introduced here: https://github.com/RoamJS/query-builder/pull/190
couldn't add a regular arrow that wasn't connected to non-shapes and lines console errored
https://www.loom.com/share/bb176761e62d4c1ab765670378a37a71
=> bug fix: add check for shape.type on dragging_handle

src/components/Kanban.tsx
https://www.loom.com/share/9b64bf644e1e414aa1fc52355b5da616
cannot drag past overflow: https://github.com/react-grid-layout/react-draggable/issues/639
=> Remove Kanban drag Bounds

src/utils/getExportTypes.ts
removed here: https://github.com/RoamJS/query-builder/pull/126
requested by Ivo via [slack](https://roamresearch.slack.com/archives/C012WK8E9DK/p1701686906453949)
Tests:
https://www.loom.com/share/346e9acd391b471f82b664a14dff3377
=> Re-add CSV export type

src/components/TldrawCanvas.tsx
`createExistingRelations()` is being called on paste which recreates existing relations
https://www.loom.com/share/dc8514a61267427d9d58c4508d438aa5
=> Tldraw - Fix duplicate relations on paste

src/components/Export.tsx, src/components/TldrawCanvas.tsx
https://www.loom.com/share/3c109f4a076c4143acaa2098b2554038
=> Tldraw - optimize placement on node import 

src/components/TldrawCanvasLabelDialog.tsx
https://www.loom.com/share/26749dd0c3ae49e69a72ae0cc921b770
=> Add focus to input element when adding referenced node

src/components/Kanban.tsx
- add `date-format` support
- change `card.result.uid` to selected `displayUid`
- add support for `link` view in card display
- handle no uid in card display
=> Kanban Card - Additional View Support

patches/@tldraw+tldraw++@tldraw+editor+2.0.0-canary.ffda4cfb.patch, src/components/TldrawCanvas.tsx
https://www.loom.com/share/db47211b0c6b44e5821cf7b62364de5c
=> Canvas - add restrictions on editing relation arrows

src/components/ResultsView.tsx, src/utils/postProcessResults.ts
Tests (*no sound)
https://www.loom.com/share/c355a731a3ac4228b946eeecadbd1254
=> Add support for greater than and less than column filter types

src/components/DiscourseNodeMenu.tsx, src/components/TldrawCanvas.tsx, src/utils/createDiscourseNode.ts, src/utils/formatUtils.ts
https://www.loom.com/share/c36f3c81274c4b6f8cac764b24f9fa22
=> Canvas - Convert image shape to dgraph node

src/components/TldrawCanvas.tsx
https://www.loom.com/share/91692271ab264408a489bdd244fe7fc8
=> Canvas bug fix

package-lock.json, package.json, src/components/Kanban.tsx, src/components/ResultsView.tsx
https://www.loom.com/share/a7468e711ac74aee95533f85a704e773
=> Kanban - Change max columns and update on group by/display change

src/components/Kanban.tsx, src/components/ResultsView.tsx, src/index.ts
https://www.loom.com/share/201f5e6fd8804819ad2e8efa537bbf7b
=> Kanban Pagination

src/components/DiscourseContext.tsx, src/components/Export.tsx, src/utils/getExportTypes.ts
requires https://github.com/samepage-network/samepage.network/pull/126
=> Add PDF Export type

src/index.ts, src/utils/parseQuery.ts
PR'd to build `/release` for client testing.
=> add fireQuerySync to window object

package-lock.json, package.json, src/components/TldrawCanvasLabelDialog.tsx, src/utils/formatUtils.ts
will adding to discourse context
=> Refactor getReferencedNodeInFormat()

src/discourseGraphsMode.ts, src/utils/getExportTypes.ts
- refactor frontmatter handling to function
- escape yaml title
- escape `"` in title
- add link type: `roam url` (`[link tex](https://roamresearch.com/#/app/yourGraph/uid)`)
=> Export: Add URL link type

.github/workflows/main.yaml, src/components/Export.tsx, src/components/ExportGithub.tsx
https://www.loom.com/share/0a446807534446558d9b160969a76e81
=> add Github destination

src/components/GitHubSync.tsx
replaces the `return null` component with a comment uid cache and a single block observer at the feature's root.
=> add comment cache

package-lock.json, package.json, src/components/DefaultFilters.tsx, src/index.ts
https://www.loom.com/share/dff8fdafd1204d7e8ebc4bf26fbe646c
Reported by jpanico via [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1716040694684149)
Looks like this causes makes an unpleasant UI as well ... will ping roam devs in the Roam Depot PR
=> remove min width on roam settings input elements

package-lock.json, package.json, src/components/CanvasDrawer.tsx, src/components/TldrawCanvas.tsx, src/index.ts
https://www.loom.com/share/aaa7d2b638b44b5fa793b8b3fcca8e37
=> Add Open Canvas Drawer  to Tldraw context menu

src/utils/conditionToDatalog.ts
to 
- is referenced by block in page with title
- has title
- references title
- is in page with title
- created by
- edited by
=> Add {current user} as target option

docs/query-builder.md
Reference Issues
https://github.com/RoamJS/query-builder/issues/272
https://github.com/RoamJS/smartblocks/issues/120
Flexible format PR
https://github.com/RoamJS/query-builder/pull/60
Inputs PR
https://github.com/RoamJS/query-builder/pull/62
=> Update SmartBlock Command Docs with output format and input variables (Closes #272)

src/utils/registerDiscourseDatalogTranslators.ts
=> dgraph translator fix (Closes #275)

src/utils/createDiscourseNode.ts
https://www.loom.com/share/2a191c70d0114f5caec2343081a84465
=> add key image support if discourse template is uses smartblocks
