package-lock.json
package.json
src/components/CytoscapePlayground.tsx
src/components/DiscourseRelationConfigPanel.tsx
src/utils/deriveDiscourseNodeAttribute.ts

Before the changes, the extension was 1.6MB, all packaged:
Now, the extension is just 0.6MB now that it uses Roam's bundled packages by default - that's a full megabyte smaller! 62% reduction.
These changes were required for DG to go live in Roam Depot

Using Roam's bundled cytoscape/insect to reduce bundle size by 1MB

---

src/utils/fireQuery.ts

Having some trouble with which characters get escaped on user input for a regex expression when creating `new RegExp` and how to deal with that.
All of these queries work in VSCode on the same input.  I feel that would be a poor user experience.
Let me know your thought @dvargas92495

add select regex from condition target

---

package-lock.json
package.json
src/index.ts

related to https://github.com/dvargas92495/roamjs-query-builder/issues/22
@dvargas92495, could it be the case that `runSortReferences()` isn't being called on load?
`if (!!extensionAPI.settings.get("sort-references")) {toggleSortReferences(true);}`
seemed to fix it when testing with `Reload Developer Extensions`

add toggleSortReferences on load if true

---

package-lock.json
package.json
src/utils/fireQuery.ts

**Issue this is addressing**
Unable to filter [Discourse Graph Attributes](https://oasis-lab.gitbook.io/roamresearch-discourse-graph-extension/guides/exploring-your-discourse-graph/discourse-attributes)
Although this does fix the Discourse Graph Attribute issue, I haven't put a lot of thought into other possible negative downstream effects.  I tested a regular Attribute that had numbers and a regex selection of numbers, both worked.
Before
After

getEnglishQuery change output number toString

---

package-lock.json
package.json
src/utils/runSortReferences.ts

@dvargas92495 for [Sort References Bug](https://roamresearch.slack.com/archives/C016N2B66JU/p1675448161078559)
`getPageTitleValueByHtmlElement(sortContainer)` is still required for Daily Notes Page
`getCurrentPageUid()` returns today's date on DNP which is what `/^([0-9]{2}-){2}[0-9]{4}$/.test(currentPageUID)` is looking for.
I feel like this isn't ideal, and it gives a false positive for any day page, but that code still works regardless on those pages.
also `npm version patch` errored, but still went to 1.1.8

Sort ref bug

---

src/index.ts

Something I'm looking to add for agency's purpose.
I'm gonna be running a QB table _per_ client. Then, I want my DNP to return just the _first_ item from each board

Adding an optional limit arg to the QUERYBUILDER cmd

---

src/utils/compileDatalog.ts

Query for Discourse Sources failed.
```
[:find
(pull ?node [:block/string :node/title :block/uid])
(pull ?node [:block/uid])
:where
[(re-pattern "^@(.*?)$") ?@.*?$-regex]
[?node :node/title ?node-Title]
[(re-find ?@.*?$-regex ?node-Title)]
]
```
Error message was: `Invalid character: @ found while reading symbol.`

add @ for sources

---

package-lock.json
package.json
src/components/QueryEditor.tsx
src/components/ResultsView.tsx
src/index.ts
src/utils/conditionToDatalog.ts
src/utils/fireQuery.ts
src/utils/runQuery.ts

If you want to create a backlog for multiple clients or users, you need to create separate query builder instances for each one.
This allows users to only have one query builder instance that can be used across multiple values for a particular field.
We're starting with the SB use case, but I still need to go through all of the usages of `fireQuery` to see what can apply.
Adding you to the PR now for visibility, no need for review yet

Supporting Inputs

---

package-lock.json
package.json
src/utils/compileDatalog.ts

`Cannot compare :block/parents to page`
`?April13th,2023`
```
[:find
(pull ?node [:block/string :node/title :block/uid])
(pull ?node [:block/uid])
:where
[?April13th,2023 :node/title "April 13th, 2023"]
[?node :block/page ?April13th,2023]
]
```

add comma to toVar for pages with commas

---

src/components/MessageBlock.tsx
src/index.ts

Roam has this concept of Changing Block View:
This brain blasted me into thinking we should allow users to create their own custom views of data to replace other pieces of UI.
This is one such use case. For now, the component is very specific. But in SamePage, we will want to allow users to create their own UIs instead, similar to smartblocks and queries. Ongoing, SB and QB will continue to serve as testing beds for ideas we want to generalize into SamePage
I wouldn't try to set this up locally (again, it's very custom to a specific user), but would rather review the idea and ask related questions if there are any

Exploring ideas around custom view types in graph

---

package-lock.json
package.json
src/components/TldrawCanvas.tsx

When editing label was still broken.
This was the real problem:

Tldraw arrow label fix editing

---

package-lock.json
package.json
src/components/ResultsTable.tsx

added `data-column-title` to target specific columns
changed `data-cell-{key}` to `data-cell-content` to target specific content patterns across all columns

Add data-column-title to results view

---

src/components/TldrawCanvas.tsx

User was experiencing severe UX issues when adding a node
- dialog box popup up multiple times
- multiple nodes being added
Looks like these lines are partially to blame.  Removing them removes the issue, but also removes ability to edit a node. 
Merging thing to give user required functionality.  Will loop back to see what a proper fix would look like.
They were added in #72 .  Let me know if removing these would cause any other breaking changes @dvargas92495

comment out useEffect to set EditLabelOpen

---

package-lock.json
package.json
src/components/TldrawCanvas.tsx

looks like `setIsEditLabelOpen(false);` was missing from `onSuccess`

Canvas add/edit node dialog fix

---

package-lock.json
package.json
src/components/Export.tsx
src/components/QueryDrawer.tsx
src/components/ResultsView.tsx
src/components/TldrawCanvas.tsx
src/index.ts

- [-] Remove "Insert Results" from header
Customer wanted to keep it there, so instead
What's left
Also, blueprint is handling setting shown tabs/panel, might need to make that controlled by us because `Export Discourse Graph` shows `Send To` as first panel.

add "send to canvas" on export

---

docs/query-builder.md
package-lock.json
package.json
src/components/QueryEditor.tsx
src/components/QueryPage.tsx
src/index.ts

https://www.loom.com/share/fa9bb926fda44dff8e4700c700cc5e18

addCommand "Create Query Block" and "Preview" kb shortcut

---

package-lock.json
package.json
src/components/Kanban.tsx
src/components/ResultsView.tsx
src/index.ts

https://www.loom.com/share/91f0c3762d5a424a88b7a2eb2781391b

Update Kanban Cards to display selections

---

package-lock.json
package.json
src/utils/compileDatalog.ts

add `~` and \` to be replaced when creating variables in `compileDatalog`

Add characters to be replaced in toVar

---

src/components/TldrawCanvas.tsx

This pull request fixes the issue with arrow label line breaks and font choice hijacking in the TldrawCanvas component. The width calculation was causing the letters to line break, and Roam was hijacking the font choice. This PR includes a temporary fix by adding padding, setting white-space to nowrap, and specifying the font-family as var(--rs-font-sans) for the rs-arrow-label class.
☝ yay AI ✨

Fix arrow label line break issue and font choice hijacking

---

package-lock.json
package.json
src/components/DiscourseNodeMenu.tsx
src/components/Kanban.tsx
src/components/ResultsView.tsx
src/components/TldrawCanvas.tsx
src/index.ts
src/utils/formatUtils.ts

I'm unsure how we should handle dragging when `activeSort` is set.
Use cases:
Drag to new column to change attribute
- my intuition says that `activeSort` should be maintained
Drag to reposition in same column
- currently not supported, `activeSort` is maintained

add activeSort support for Kanban view

---

src/components/Export.tsx
src/discourseGraphsMode.ts
src/utils/getExportTypes.ts
src/utils/types.ts

Just before creating this PR I realized I missed something 😑 (which is the reason for all the comment edits)
I thought I had an epiphany here (see video 😅) but in my dev branch I wasn't accounting for the results being passed by the `Export Discourse Graph` command.  But it turns out even with those results being passed in, because of `block` / `page`, the `gatherings` output gets significantly increased.  (even more than my video shows)
https://www.loom.com/share/664fd3cc2125492cbb16009500b9d0a8
Looks like the `Set` check clears it up.
And I'm curious, @dvargas92495, what is the purpose of the `matchDiscourseNode` filter in `getPageData`? (see comment in review)

Optimize Discourse Export

---

src/components/Kanban.tsx

Ported over from [ResultsView](https://github.com/RoamJS/query-builder/blob/c9354da3519f3b60103938f00306920519571004/src/components/ResultsTable.tsx#L311C1-L336)
I removed the `ctrl click` support, `onMouseDown`, and `onContextMenu`.
Should those still be included?  
I think `ctrlClick`'s was from `Query Drawer`.  Might be worth removing altogether?  
What problem are `onMouseDown` and `onContextMenu` solving?

support link view for kanban selections

---

src/utils/predefinedSelections.ts

from these changes: https://github.com/RoamJS/query-builder/pull/146
`oldValue` wasn't updated to `previousValue` which is:
```javascript
const previousValue = toCellValue({
value: result[columnKey],
uid: columnUid?.toString(),
});
```
If the selection `label` was different than `data` (attribute name), `oldValue` would return `""` and prepend the block with the new value.
eg:
as `status` select `Status`
as `abc` select `Status`

Refactor predefinedSelections update function

---

src/components/Export.tsx
src/components/ResultsView.tsx
src/components/TldrawCanvas.tsx
src/utils/calcCanvasNodeSizeAndImg.ts

when the first column is renamed via a `node` selection, `r.text` was undefined in `Share Data` > `Send To`

handle custom first column name

---

src/components/CanvasDrawer.tsx
src/components/TldrawCanvas.tsx
src/index.ts

https://www.loom.com/share/70aef098714a47cc8cb54f0c166a79d0

Canvas Drawer

---

package-lock.json
package.json
src/components/TldrawCanvas.tsx
src/components/TldrawCanvasLabelDialog.tsx

https://www.loom.com/share/cf6b07dcce304f59b5a7425ce383724b

get current roam node content when dialog opens

---

package-lock.json
package.json
src/utils/conditionToDatalog.ts

- add regex support for `with text`
- add case-insensitive support for regex `with text` and `has title` (`/some text/i`)

add regex support to 'with text', handle case insensitive regex

---

src/discourseGraphsMode.ts
src/utils/formatUtils.ts
src/utils/getExportTypes.ts

From a client request to add referenced nodes to exports.
EG: Format = [[EVD]] - {content} - {Source}
then add "Source: [[The source page title]]" to the appended Discourse Context on export
Another workaround for `format` over `specification`, re: https://github.com/RoamJS/query-builder/issues/189 😞

Add referenced node to exported discourse context

---

src/components/ExportGithub.tsx

`process` returning undefined.
Build process not catching it?  unsure.  Will inspect later.

hardcode github app id

---

package-lock.json
package.json
src/components/ExportGithub.tsx

This will be used when the extension doesn't allow for a popup window to pass a `postMessage` (eg: electron apps).
Requires: https://github.com/samepage-network/samepage.network/pull/154

Check samepage for access-token on Authorize

---

package-lock.json
package.json
src/components/Export.tsx

So the user can open the page they just sent the results to in main window or sidebar.  Or just ignore it.
Requires: https://github.com/RoamJS/roamjs-components/pull/25
https://www.loom.com/share/0025b7aeac864cadadd1fadbc73ea27c

add JSX and pageUid to renderToast on Export Send To

---

package-lock.json
package.json
src/components/DefaultFilters.tsx
src/index.ts

Reverts RoamJS/query-builder#258
I rushed 258.  Not only did I merge into the wrong branch ... `.rm-settings .rm-extensions-settings input[type="text"]` would affect all extension, not just qb.  🙄

Revert "remove min width on roam settings input elements"

---

docs/query-builder.md
src/utils/isDiscourseNode.ts

- require `uid`, remove `nodes` params
What was the use case of having `nodes` as a param? @dvargas92495 
I checked all instances where we use `isDiscourseNode` and it looks like we are only using `uid` at the moment.
Related to https://github.com/RoamJS/roamjs-components/pull/26

isDiscourseNode small refactor

---

src/components/TldrawCanvas.tsx

Users were getting Image fails when the node had 10+ relationships defined.
There is still a significant delay when adding these nodes that should be addressed.
When discourse queries are outsourced to SamePage, that would work.
Or we make `createExistingRelations` opt in / on demand.

increase timeout and await setSizeandImageProps

---

src/components/DiscourseContext.tsx
src/components/ResultsTable.tsx
src/discourseGraphsMode.ts
src/utils/fireQuery.ts
src/utils/getDiscourseContextResults.ts
src/utils/getDiscourseRelations.ts

this is the frontend support for https://github.com/samepage-network/roam-samepage/pull/22
mostly just adds a flag, some loading state, and minor adjustments to help the backend

add support for backend querying of discourse context

---

package-lock.json
package.json
src/components/DiscourseContext.tsx
src/components/DiscourseContextOverlay.tsx

Discourse Overlay sends `results` which is an array, of `{label:string,results:[]}` so even if it's empty it won't trigger the `onRefresh()` which sets `setLoading(false)`
`!results` is still useful for `ReferenceContext` and `ResultsTable`
https://github.com/RoamJS/query-builder/blob/6675ed77bf5b456d7a5b4bb65dd658e598367a20/src/components/ReferenceContext.tsx#L77
https://github.com/RoamJS/query-builder/blob/7dd7e4da9946799e1a6cd38285920ff3c47be3c3/src/components/ResultsTable.tsx#L581

Discourse Overlay no results fix (Closes #278)

---

package-lock.json
package.json
patches/@tldraw+tldraw++@tldraw+editor+2.0.0-canary.ffda4cfb.patch
patches/@tldraw+tldraw++@tldraw+ui+2.0.0-canary.ffda4cfb.patch

EDIT: we can just handle the pasted svg strings the same way further downstream.
--------------
Pasting files is handled here: https://github.com/RoamJS/query-builder/blob/main/patches/%40tldraw%2Btldraw%2B%2B%40tldraw%2Beditor%2B2.0.0-canary.ffda4cfb.patch
But it is still possible to `Copy as SVG`, then paste that clipboard which is potentially a very large string.  This is a quick safeguard for that.  
We will handle this properly in the 2.3.0+ upgrade.

Tldraw - handle pasted svg strings

---

package-lock.json
package.json
src/components/tldraw/Tldraw.tsx

use case: node title was changed off canvas, so relation created would use old title stored in node props
This is a quick fix this specific use case, but in the tldraw upgrade we should `addPullWatch` on all node uid's to watch for title changes, and update canvas nodes accordingly.  
More discussion on that here: https://github.com/RoamJS/query-builder/issues/284

Tldraw - grab current title on relation create

---

src/components/DiscourseNodeMenu.tsx
src/discourseGraphsMode.ts
src/index.ts

`\` is often used in LaTeX so users want the ability to disable it as the global node menu trigger.
I'd probably like to phase out the global trigger in favor of the command palette, but I worry that users will request a "modifier" free option, which I don't think the command palette supports.
https://www.loom.com/share/d1ab1bb4e75446aebdb186fe39dccf5b

add command palette, add disable global

---

src/utils/matchDiscourseNode.ts

https://www.loom.com/share/033f6d8d5915456c847e6d38591a148d
for single clause `has title` specification (which is the de facto standard and equivalent of `format`)

matchDiscourseNode early return for single "has title" clause

---

src/components/ResultsTable.tsx
src/utils/predefinedSelections.ts

Added `{key}-url` to `Result` if valid `URL` (only in last selection test)
Request from Ivo via [Slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1735568062452869)
> When the attribute value is a URL, how to make it work as such without using embed in the Query Builder column view?

handle attribute URLs

---

docs/query-builder.md
src/utils/conditionToDatalog.ts

`{this page}` - matches the page in which the query is run

Add Condition target {this page}

---

src/components/Export.tsx
src/components/tldraw/Tldraw.tsx
src/utils/calcCanvasNodeSizeAndImg.ts
src/utils/sendErrorEmail.ts

create sendErrorEmail component, don't send if encrypted/offline

---

docs/query-builder.md

https://github.com/RoamJS/query-builder/issues/304
- Introduced OR and NOT OR operators for complex queries.
- Detailed steps for creating and managing OR/NOT OR branches.
- Provided practical examples for using these operators in queries.

Add documentation for logical operators in Query Builder
